[package]
name = "challenge-7"
version = "0.1.0"
authors = ["William Oldham <wegg7250@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rprompt = "1.0.3"
